[package]
name = "preempt-do"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
named-semaphore = { version = "0.1", path = "../" }
clap = { version = "4", features = ["derive"] }
anyhow = "1"
